export interface AppCatalogItem {
  id: string;
  name: string;
  slug: string;
  category: string;
  featuredRank: number;
  docsUrl?: string;
}

const docsByName: Record<string, string> = {
  Stripe: "https://docs.stripe.com/webhooks",
  GitHub: "https://docs.github.com/en/webhooks",
  Shopify: "https://shopify.dev/docs/apps/build/webhooks",
  Slack: "https://api.slack.com/apis/web-api/using-the-conversations-api#events",
  HubSpot: "https://developers.hubspot.com/docs/api/webhooks",
  Twilio: "https://www.twilio.com/docs/usage/webhooks",
  Vercel: "https://vercel.com/docs/webhooks",
  GitLab: "https://docs.gitlab.com/user/project/integrations/webhooks/",
  Discord: "https://discord.com/developers/docs/events/webhook-events",
  Calendly: "https://developer.calendly.com/api-docs/eb8ee72701f99-webhook-subscriptions",
  Linear: "https://developers.linear.app/docs/graphql/webhooks",
  Clerk: "https://clerk.com/docs/webhooks/overview",
  Auth0: "https://auth0.com/docs/customize/actions/explore-triggers/password-reset-triggers",
  Notion: "https://developers.notion.com/reference/webhooks",
  OpenAI: "https://platform.openai.com/docs/guides/webhooks",
};

const appGroups: Record<string, string[]> = {
  "Developer Tools": [
    "GitHub",
    "GitLab",
    "Bitbucket",
    "CircleCI",
    "Buildkite",
    "Jenkins",
    "Vercel",
    "Netlify",
    "Render",
    "Railway",
    "Fly.io",
    "Sentry",
    "Postman",
    "Retool",
    "Supabase",
    "Neon",
    "PlanetScale",
    "Linear",
    "Jira",
    "Asana",
    "Trello",
    "ClickUp",
    "Basecamp",
    "Shortcut",
    "Figma",
    "Miro",
    "Loom",
    "Framer",
    "Webflow",
    "Zapier",
  ],
  "Payments & Billing": [
    "Stripe",
    "Adyen",
    "PayPal",
    "Square",
    "Braintree",
    "Chargebee",
    "Recurly",
    "Paddle",
    "Lemon Squeezy",
    "FastSpring",
    "Zuora",
    "Mollie",
    "Razorpay",
    "Checkout.com",
    "Wise",
    "Airwallex",
    "Xero",
    "QuickBooks",
    "FreshBooks",
    "ChargeOver",
  ],
  "Commerce & Orders": [
    "Shopify",
    "WooCommerce",
    "BigCommerce",
    "Magento",
    "Commerce Layer",
    "Medusa",
    "Snipcart",
    "Gumroad",
    "Etsy",
    "eBay",
    "Amazon Seller Central",
    "Faire",
    "Loop",
    "ShipStation",
    "Shippo",
    "EasyPost",
    "Printful",
    "Printify",
    "Recharge",
    "Cratejoy",
  ],
  "CRM & Sales": [
    "HubSpot",
    "Salesforce",
    "Pipedrive",
    "Copper",
    "Close",
    "Attio",
    "Apollo",
    "Gong",
    "Outreach",
    "Salesloft",
    "Affinity",
    "Zoho CRM",
    "Monday.com",
    "Insightly",
    "Keap",
    "Freshsales",
    "HighLevel",
    "Nutshell",
    "Streak",
    "Capsule",
  ],
  "Marketing Automation": [
    "Mailchimp",
    "Klaviyo",
    "Braze",
    "Customer.io",
    "Iterable",
    "Omnisend",
    "ActiveCampaign",
    "ConvertKit",
    "Beehiiv",
    "Campaign Monitor",
    "Drip",
    "MailerLite",
    "Postscript",
    "Loops",
    "Ortto",
    "Marketo",
    "Pardot",
    "Unbounce",
    "Brevo",
    "OneSignal",
  ],
  "Support & Success": [
    "Zendesk",
    "Intercom",
    "Freshdesk",
    "Help Scout",
    "Front",
    "Gorgias",
    "Crisp",
    "Kustomer",
    "Dixa",
    "Gladly",
    "Talkdesk",
    "Aircall",
    "Dialpad",
    "Reamaze",
    "Tidio",
    "LiveChat",
    "Ada",
    "ChurnZero",
    "Vitally",
    "Planhat",
  ],
  "Communication & Scheduling": [
    "Slack",
    "Discord",
    "Microsoft Teams",
    "Twilio",
    "Postmark",
    "Mailgun",
    "Resend",
    "Vonage",
    "MessageBird",
    "SendGrid",
    "Zoom",
    "Calendly",
    "Cal.com",
    "SavvyCal",
    "Typeform",
    "Tally",
    "Jotform",
    "Google Chat",
    "Eventbrite",
    "Meetup",
  ],
  "Productivity & Collaboration": [
    "Notion",
    "Airtable",
    "Google Sheets",
    "Google Drive",
    "Dropbox",
    "Box",
    "Confluence",
    "Todoist",
    "Coda",
    "Smartsheet",
    "Wrike",
    "Teamwork",
    "Baserow",
    "Aha!",
    "Mural",
    "FigJam",
    "Lucid",
    "Fibery",
    "Height",
    "Motion",
  ],
  "Data & Analytics": [
    "Segment",
    "RudderStack",
    "Mixpanel",
    "Amplitude",
    "PostHog",
    "Heap",
    "Fullstory",
    "Hotjar",
    "Databox",
    "Census",
    "Hightouch",
    "Fivetran",
    "Airbyte",
    "dbt Cloud",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Looker",
    "Metabase",
    "Tableau",
  ],
  "Security & Identity": [
    "Auth0",
    "Clerk",
    "Okta",
    "WorkOS",
    "Descope",
    "Stytch",
    "1Password Events",
    "Snyk",
    "Vanta",
    "Drata",
    "Tailscale",
    "Cloudflare Zero Trust",
    "LaunchDarkly",
    "Permit.io",
    "Aserto",
    "Teleport",
    "Twingate",
    "JumpCloud",
    "FusionAuth",
    "Keycloak",
  ],
  "Infrastructure & Ops": [
    "Cloudflare",
    "PagerDuty",
    "Opsgenie",
    "Datadog",
    "New Relic",
    "Honeycomb",
    "Grafana Cloud",
    "Better Stack",
    "Logtail",
    "UptimeRobot",
    "Cronitor",
    "Statuspage",
    "Incident.io",
    "FireHydrant",
    "Terraform Cloud",
    "Pulumi Cloud",
    "Backblaze B2",
    "DigitalOcean",
    "Akamai",
    "MongoDB Atlas",
  ],
  "AI & Agents": [
    "OpenAI",
    "Anthropic",
    "Langfuse",
    "LangSmith",
    "Replicate",
    "Modal",
    "Fal",
    "AssemblyAI",
    "ElevenLabs",
    "HeyGen",
    "Runway",
    "Tavus",
    "Synthesia",
    "Vapi",
    "Retell AI",
    "Bland",
    "Deepgram",
    "Hume",
    "Recall",
    "Mem0",
  ],
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const seenIds = new Map<string, number>();

export const APPS: AppCatalogItem[] = Object.entries(appGroups).flatMap(([category, names]) =>
  names.map((name) => {
    const baseId = slugify(name);
    const nextCount = (seenIds.get(baseId) ?? 0) + 1;
    seenIds.set(baseId, nextCount);

    return {
      id: nextCount === 1 ? baseId : `${baseId}-${nextCount}`,
      name,
      slug: slugify(name),
      category,
      featuredRank: 0,
      docsUrl: docsByName[name],
    };
  }),
).map((app, index) => ({
  ...app,
  featuredRank: index,
}));

export const appById = new Map(APPS.map((app) => [app.id, app]));
